import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-linear-to-br from-gray-950 via-zinc-900 to-stone-900`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* {children} */}
          <Header/>
        
      <main className=" relative min-h-screen container  mx-auto pt-40 md:pt-32">
        {/* glow effect */}
        <div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden">
          <div className="absolute top-0 left-1/4 w-96 h-96 bg-pink-600/20 rounded-full blur-3xl"/>
          <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-orange-600/20 rounded-full blur-3xl"/>
          {/* <div className=""/> */}
        </div>
        {/* <div>     {children}</div> */}
        <div className="relative  z-10 min-h-[70vh]">     {children}</div>
          {/* footer */}
          <footer className="border-t border-gray-800/50 py-8 px-6 mx-w-7xl mx-auto">
          <div className="text-gray-50">Made With Love </div></footer>
      </main>
          </ThemeProvider>
      </body>
    </html>
  );
}
